version: '3.8'
services:
  kc-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports: ["5433:5432"]
    volumes: [kc_data:/var/lib/postgresql/data]

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kc-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8080:8080"]
    volumes:
      - ./realm-export:/opt/keycloak/data/import
    depends_on: [kc-db]
volumes:
  kc_data:
