version: "3.8"
services:
  app-db:
    image: postgres:16
    environment:
      POSTGRES_DB: fma
      POSTGRES_USER: fma
      POSTGRES_PASSWORD: fma
    ports: ["5434:5432"]
    volumes: [app_pg:/var/lib/postgresql/data]
volumes:
  app_pg:
